EVALUATE
ROW (
    "TotalNetworkKPIRows",
        COUNTROWS ( 'NetworkKPI' ),

    "RowsAfterActiveDateFilter",
        CALCULATE (
            COUNTROWS ( 'NetworkKPI' ),
            'ActiveDate'[DateValue] = DATE ( 2026, 9, 14 )
        ),

    "RouteCountWithoutDateFilter",
        MAX ( 'NetworkKPI'[RouteCount] ),

    "RouteCountWithDateFilter",
        CALCULATE (
            MAX ( 'NetworkKPI'[RouteCount] ),
            'ActiveDate'[DateValue] = DATE ( 2026, 9, 14 )
        )
)